name = "zmail"
main = "worker/src/index.ts"

# 打包配置
minify = true # 生产环境压缩代码
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-03-01"
keep_vars = true

# 启用 D1 数据库
# 注意：这里的 binding 是固定的 "DB"，database_name 和 database_id 将由 GitHub Action 动态替换
[[d1_databases]]
binding = "DB"
database_name = "zmail"  # 这是 D1 数据库名称的占位符
database_id = "610b260d-3c74-4035-a29f-a3d64eb61929"      # 这是 D1 数据库 ID 的占位符

# 设置域名
# 注意：这里的 VITE_EMAIL_DOMAIN 将由 GitHub Action 动态替换
[vars]
VITE_EMAIL_DOMAIN = "1.e.4.a.0.6.3.0.0.0.7.4.0.1.0.0.2.ip6.arpa,2.e.4.a.0.6.3.0.0.0.7.4.0.1.0.0.2.ip6.arpa,3.e.4.a.0.6.3.0.0.0.7.4.0.1.0.0.2.ip6.arpa,4.e.4.a.0.6.3.0.0.0.7.4.0.1.0.0.2.ip6.arpa,5.e.4.a.0.6.3.0.0.0.7.4.0.1.0.0.2.ip6.arpa"   # 这是邮箱域名的占位符

# 配置邮件处理
[triggers]
crons = ["0 * * * *"]  # 每小时运行一次清理任务

[build]
command = "pnpm run build"

[assets]
binding = "ASSETS"
directory = "frontend/dist"
not_found_handling = "single-page-application"

# 默认开启日志，方便调试
[observability]
enabled = false
head_sampling_rate = 1 # optional. default = 1.
